- src/ssort/_bindings.py
- tests/test_bindings.py
Adds basic support for sorting code with bindings created using the walrus operator.
Requirements satisfied by bindings created within the same expression remain broken.  For example, the following is valid python, but will be rejected by ssort:
```python
(a := 1) + a
```
Hopefully nobody is going to do that though.
> Walrus bindings

- setup.cfg
Fixes #21
Commit 4b4e1a7d959fd5195be5ccf7c376a42c15d9c5f3 added python 3.8+ syntax to `topological_sort` so setup.cfg needs to reflect that minimum version requirement.
https://docs.python.org/3/whatsnew/3.8.html#positional-only-parameters
> Bump minimum python version

- src/ssort/_bindings.py
- src/ssort/_requirements.py
- tests/test_bindings.py
- tests/test_requirements.py
Discover bindings made in the format spec of a format string.
Simple example illustrating how a variable can be bound inside a format spec:
```
>>> x
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'x' is not defined
>>>
>>> f"{3.1415:{(x := 0.3)}}"
'3.14'
>>>
>>> x
0.3
```
> Discover bindings made in format spec of format string

- src/ssort/_ssort.py
- tests/test_ssort.py
This is done to better support the common pattern of using an inner class to contain class metadata, as used in the django ORM and pydantic.  Previously, inner classes were treated in the same way as methods and mixed into the middle of the class.
Resolves #31.  Prompted by discussion in #11.
> Move inner classes to top of body

- src/ssort/__init__.py
- src/ssort/_dependencies.py
- src/ssort/_exceptions.py
- src/ssort/_main.py
- src/ssort/_ssort.py
- tests/test_dependencies.py
- tests/test_samples.py
This is prep work for skipping files based on `.gitignore` (#23).
> Centralize error reporting at the top of the stack

- src/ssort/_dependencies.py
- src/ssort/_exceptions.py
- src/ssort/_main.py
- src/ssort/_ssort.py
- tests/test_error_hooks.py
This just makes the `on_unresolved` callback a little bit more consistent with the other hooks.
> Pass message to on_unresolved hook

- src/ssort/_parsing.py
- src/ssort/_ssort.py
- tests/test_dependencies.py
- tests/test_split.py
- tests/test_statements.py
This is mostly setting the scene for renaming the `on_syntax_error` hook to `on_parse_error` to avoid name clash with stdlib `SyntaxError`.  It should also help a little bit with adding type annotations.
> Fix awkward reuse of `split` function by creating `parse` wrapper

- src/ssort/__init__.py
- src/ssort/_exceptions.py
- src/ssort/_main.py
- src/ssort/_parsing.py
- src/ssort/_ssort.py
- tests/test_error_hooks.py
This gives better control over error reporting, and is more consistent with how other errors are handled.  It makes it practical to fix some stupid bugs in the hook where attributes are being set the wrong way.
> Replace SyntaxError with custom ParseError and fix corresponding hooks

- pyproject.toml
- setup.cfg
- src/ssort/_files.py
- src/ssort/_main.py
- tests/test_files.py
I ended up scrapping the `_files` module pulled in from `black` because I ran into a number of issues:
1. There is a lot of code which is specific to `black` and not applicable to `ssort`.
2. `.gitignore` files outside of the root are ignored as you mentioned in #45
3. Only a single project root is allowed.
4. Symbolic links can't be resolved outside the project root.
5. And, generally, there was a lot of complexity which was unnecessary for just this single feature.
The new `_files` implementation I put together solves all the above issues.
> Exclude files in .gitignore

- src/ssort/_files.py
- src/ssort/_main.py
- tests/test_executable.py
Improves messages in the following cases:
1. A provided file does not exist.
2. A directory was provided but that directory contains no Python files.
Changed behavior:
1. Allow processing of files even if they do not have a `.py` extension.
> Improve file related error messages

- src/ssort/_ssort.py
- tests/test_ssort.py
Properly handle files with no statements. The existing behavior is to delete everything in the file, including any comments.
> Empty file fix

- src/ssort/_exceptions.py
- src/ssort/_ssort.py
- tests/test_error_hooks.py
Fixed signature of `_on_wildcard_import_raise` and `_on_wildcard_import_ignore`. Existing behavior causes a `TypeError` to be raised if a wildcard import is encountered and either `on_wildcard_import="ignore"` or `on_wildcard_import="raise"` is specified.
> Wildcard import callback fix

- src/ssort/_main.py
- src/ssort/_ssort.py
- src/ssort/_utils.py
- tests/test_executable.py
- tests/test_ssort.py
I think this should resolve #61.  Same problem with duplicate implementations as with encoding, only slightly worse because the newline detection logic will always run twice.  Should only result in a single wasted `re.search` scan over the first line of the file.
> Add support for detecting and preserving different newline types

- .github/workflows/ci.yaml
- src/ssort/_main.py
- src/ssort/_utils.py
- tests/test_executable.py
Will do a separate one for OSX once this is passing.
> Run tests on windows as well as linux

- README.rst
Thanks a ton for your work!
Implementing this means one less thing to keep up-to-date in the readme. Current example fails:
```
[INFO] Initializing environment for https://github.com/bwhmather/ssort.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '0.11.5')
return code: 1
expected return code: 0
stdout: (none)
stderr:
error: pathspec '0.11.5' did not match any file(s) known to git
```
Whereas new example running, pre-commit automatically informs the user:
```
[WARNING] The 'rev' field of repo 'https://github.com/bwhmather/ssort' appears to be a mutable reference (moving tag / branch).  
Mutable references are never updated after first install and are not supported.  
See https://pre-commit.com/#using-the-latest-version-for-a-repository for more …
```
> Change pre-commit `rev:` to `master`

- src/ssort/_bindings.py
- src/ssort/_requirements.py
- tests/test_bindings.py
- tests/test_ssort.py
The scoping around comprehensions is a bit confusing and our logic doesn't capture it correctly. Consider this case which we currently sort incorrectly:
```python
def f():
g()
return [g for g in range(10)]
def g():
print("Called g")
```
In the above snippet, the `g()` invocation within `f` and the `g` reference within the list comprehension exist within two separate scopes. Therefore, the invocation of `g()` should NOT be considered a call to a variable within the local scope. That is, function `f` does indeed have a requirement on the global function `g`.
This PR fixes this scoping issue and introduces additional tests to assert correctness of these cases.
> Fix comprehension bindings and requirements when target conflicts with outer scope

- tox.ini
Latest version of tox doesn't like basepython colliding with environment names.  Workaround is tedious but at least works.
> Set basepython separately for each tox target

- .github/workflows/release.yaml
- pyproject.toml
My earlier concerns about build-system requirements in sdists are a complete non-issue if we distribute wheels instead.  Wheels just contain the files to install and a little bit of metadata (essentially the contents of the `project` section in `pyproject.toml`, the `LICENSE` and the `README`).  Building both fixes everything.
> Build and release wheels to PyPI

- src/ssort/_method_requirements.py
- tests/test_method_requirements.py
- tests/test_ssort.py
Resolves https://github.com/bwhmather/ssort/issues/90
> Fix detection of self argument name when positional-only

- src/ssort/_ssort.py
- tests/test_ssort.py
Required for compatibility with black 24 and to comply with out "don't reformat if ordered correctly" rule.  Fixes #113 .
> Don't reformat classes if statement order unchanged

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- src/ssort/_ast.py
- src/ssort/_parsing.py
- src/ssort/_requirements.py
- tests/test_bindings.py
- tests/test_requirements.py
- tests/test_ssort.py
- tox.ini
Also update tox and GitHub Actions to use Python 3.12 by default.
> Support traversal of TypeAlias for Python 3.12

- .github/workflows/ci.yaml
I noticed the macos actions weren't running with the old macos-11 set, so this bumps macos to 13, and while we're at it Windows to 2022. If you approve the workflow, we can see if the new image actions run without issue. Both of those are documented to cache Python 3.8-3.12 at least, so I don't expect a problem.
> Update CI images: latest which cache py 3.8-3.12

- src/ssort/_parsing.py
`pylint` tests have bitrotted/`pylint` has got better:  https://github.com/bwhmather/ssort/actions/runs/11557873213/job/32183891963?pr=119.
Something, something, pinning dependencies.
> Fix pylint warings about unassigned variables

- src/ssort/_files.py
- src/ssort/_main.py
- tests/test_executable.py
This works well in my casual testing, and can even be used in combination with regular file arguments. ~But I haven't written a formal test for it yet, so I'm marking this as a draft.~
It makes sure to write the stdin to stdout if there's a problem formatting/encoding/decoding, and if no formatting is necessary. This ensures it doesn't delete content when used as one step in a pipeline of successive formatters and linters.
> Implement stdin-stdout operation with '-' file argument

- .github/workflows/ci.yaml
- pyproject.toml
- src/ssort/_ast.py
- src/ssort/_files.py
- src/ssort/_utils.py
- tests/test_ast.py
- tests/test_bindings.py
- tests/test_method_requirements.py
- tests/test_requirements.py
- tox.ini
Removes support for Python 3.8, which became EOL on 2024-10-07:
https://peps.python.org/pep-0569/
> chore: remove Python 3.8 support
